"""
  Copyright (c) 2017 Bastian Koppelmann Paderborn University

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, see <http://www.gnu.org/licenses/>.
"""
from Instruction import *

insn = [Instruction("add"       , [RandomRegister("d") , RandomRegister("d")                                                ]),
        Instruction("add"       , [RandomRegister("d") , RandomConstant(4, 1)                                               ]),
        Instruction("add"       , [Register("d15")     , RandomRegister("d")   , RandomRegister("d")                        ]),
        Instruction("add"       , [Register("d15")     , RandomRegister("d")   , RandomConstant(4, 1)                       ]),
        Instruction("add"       , [RandomRegister("d") , Register("d15")       , RandomRegister("d")                        ]),
        Instruction("add"       , [RandomRegister("d") , Register("d15")       , RandomConstant(4, 1)                       ]),

        Instruction("add.a"     , [RandomRegister("a") , RandomRegister("a")                                                ]),
        Instruction("add.a"     , [RandomRegister("a") , RandomConstant(4, 1)                                               ]),

        Instruction("adds"      , [RandomRegister("d") , RandomRegister("d")                                                ]),

        Instruction("addsc.a"   , [RandomRegister("a") , RandomRegister("a")    , Register("d15")   , RandomConstant(2,0)   ]),

        Instruction("and"       , [RandomRegister("d") , RandomRegister("d")                                                ]),
        Instruction("and"       , [Register("d15")     , RandomConstant(8, 0)                                               ]),

        Instruction("cadd"       , [RandomRegister("d") , Register("d15")       , RandomConstant(4, 1)                      ]),
        Instruction("caddn"      , [RandomRegister("d") , Register("d15")       , RandomConstant(4, 1)                      ]),


        Instruction("cmov"       , [RandomRegister("d") , Register("d15")       , RandomConstant(4, 1)                      ]),
        Instruction("cmov"       , [RandomRegister("d") , Register("d15")       , RandomRegister("d")                       ]),
        Instruction("cmovn"      , [RandomRegister("d") , Register("d15")       , RandomConstant(4, 1)                      ]),
        Instruction("cmovn"      , [RandomRegister("d") , Register("d15")       , RandomRegister("d")                       ]),

        Instruction("eq"         , [Register("d15")     , RandomRegister("d")   , RandomConstant(4, 1)                      ]),
        Instruction("eq"         , [Register("d15")     , RandomRegister("d")   , RandomRegister("d")                       ]),

        Instruction("j"          , [JumpOffset(50)                                                                          ]),
        Instruction("jeq"        , [Register("d15")     , RandomConstant(4, 1)  , JumpOffset(4)                             ]),
        Instruction("jgez"       , [RandomRegister("d") , JumpOffset(4)                                                     ]),
        Instruction("jgtz"       , [RandomRegister("d") , JumpOffset(4)                                                     ]),
        Instruction("jlez"       , [RandomRegister("d") , JumpOffset(4)                                                     ]),
        Instruction("jltz"       , [RandomRegister("d") , JumpOffset(4)                                                     ]),
        Instruction("jne"        , [Register("d15")     , RandomConstant(4, 1)  , JumpOffset(4)                             ]),
        Instruction("jne"        , [Register("d15")     , RandomRegister("d")   , JumpOffset(4)                             ]),
        Instruction("jnz"        , [Register("d15")     , JumpOffset(8)                                                     ]),
        Instruction("jnz"        , [RandomRegister("d") , JumpOffset(4)                                                     ]),
        Instruction("jnz.a"      , [RandomRegister("a") , JumpOffset(4)                                                     ]),
        Instruction("jnz.t"      , [Register("d15")     , RandomConstant(4, 0), JumpOffset(4)                               ]),
        Instruction("jz"         , [RandomRegister("d") , JumpOffset(4)                                                     ]),
        Instruction("jz"         , [Register("d15")     , JumpOffset(8)                                                     ]),
        Instruction("jz.a"       , [RandomRegister("a") , JumpOffset(4)                                                     ]),
        Instruction("jz.t"       , [Register("d15")     , RandomConstant(4, 0), JumpOffset(4)                               ]),

# TODO: all the load instructions
        Instruction("ld.a"       , [RandomRegister("a") , RandomAbsConstant()                                               ]),
        Instruction("ld.d"       , [RandomRegister64("e") , RandomAbsConstant()                                             ]),
        Instruction("ld.da"      , [RandomRegister64("a") , RandomAbsConstant()                                             ]),
        Instruction("ld.w"       , [RandomRegister("d") , RandomAbsConstant()                                               ]),
        Instruction("ld.b"       , [RandomRegister("d") , RandomAbsConstant()                                               ]),
        Instruction("ld.bu"      , [RandomRegister("d") , RandomAbsConstant()                                               ]),
        Instruction("ld.h"       , [RandomRegister("d") , RandomAbsConstant()                                               ]),
        Instruction("ld.hu"      , [RandomRegister("d") , RandomAbsConstant()                                               ]),
        Instruction("ldmst"      , [RandomAbsConstant() , RandomRegister64("e")                                             ]),
        Instruction("swap.w"     , [RandomAbsConstant() , RandomRegister("d")                                               ]),
        Instruction("ldlcx"      , [RandomAbsConstant()                                                                     ]),
        Instruction("stlcx"      , [RandomAbsConstant()                                                                     ]),
        Instruction("stucx"      , [RandomAbsConstant()                                                                     ]),
        Instruction("st.a"       , [RandomAbsConstant() , RandomRegister("a")                                               ]),
        Instruction("st.d"       , [RandomAbsConstant() , RandomRegister64("e")                                             ]),
        Instruction("st.da"      , [RandomAbsConstant() , RandomRegister64("a")                                             ]),
        Instruction("st.w"       , [RandomAbsConstant() , RandomRegister("d")                                               ]),
        Instruction("st.b"       , [RandomAbsConstant() , RandomRegister("d")                                               ]),
        Instruction("st.h"       , [RandomAbsConstant() , RandomRegister("d")                                               ]),
        Instruction("st.q"       , [RandomAbsConstant() , RandomRegister("d")                                               ]),
        Instruction("ld.q"       , [RandomRegister("d") , RandomAbsConstant()                                               ]),
        Instruction("st.t"       , [RandomAbsConstant() , RandomConstant(3, 0), RandomConstant(1, 0)                        ]),

# Bit instructions
        Instruction("and.and.t"  , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("and.andn.t" , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("and.nor.t"  , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("and.or.t"   , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("and.t"      , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("andn.t"     , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("nor.t"      , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("or.t"       , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("ins.t"      , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("insn.t"     , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("nand.t"     , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("orn.t"      , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("xnor.t"     , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("xor.t"      , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("or.and.t"   , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("or.andn.t"  , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("or.nor.t"   , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("or.or.t"    , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.and.t"   , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.andn.t"  , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.nor.t"   , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.or.t"    , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.nand.t"  , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.orn.t"   , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.xnor.t"  , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),
        Instruction("sh.xor.t"   , [RandomRegister("d") , RandomRegister("d"), RandomConstant(5, 0), RandomRegister("d"),
                                    RandomConstant(5, 0)                                                                    ]),

        Instruction("lt"         , [Register("d15")     , RandomRegister("d")   , RandomConstant(4, 1)                      ]),
        Instruction("lt"         , [Register("d15")     , RandomRegister("d")   , RandomRegister("d")                       ]),

        Instruction("mov"        , [Register("d15")     , RandomRegister("d")                                               ]),
        Instruction("mov"        , [RandomRegister("d") , RandomConstant(4, 1)                                              ]),
        Instruction("mov"        , [Register("d15")     , RandomConstant(8, 0)                                              ]),

        Instruction("mov.a"      , [RandomRegister("a") , RandomRegister("d")                                               ]),
        Instruction("mov.a"      , [RandomRegister("a") , RandomConstant(4, 0)                                              ]),
        Instruction("mov.aa"     , [RandomRegister("a") , RandomRegister("a")                                               ]),
        Instruction("mov.d"      , [RandomRegister("d") , RandomRegister("a")                                               ]),
        #Instruction("mov"        , [RandomRegister64("e"), RandomConstant(4, 1)                                             ]),
        Instruction("mul"        , [RandomRegister("d") , RandomRegister("d")                                               ]),

        Instruction("not"        , [RandomRegister("d")                                                                     ]),

        Instruction("or"         , [RandomRegister("d") , RandomRegister("d")                                               ]),
        Instruction("or"         , [Register("d15")     , RandomConstant(8, 0)                                              ]),


        Instruction("rsub"       , [RandomRegister("d")                                                                     ]),

        Instruction("sat.b"      , [RandomRegister("d")                                                                     ]),
        Instruction("sat.bu"     , [RandomRegister("d")                                                                     ]),
        Instruction("sat.h"      , [RandomRegister("d")                                                                     ]),
        Instruction("sat.hu"     , [RandomRegister("d")                                                                     ]),

        Instruction("sh"         , [RandomRegister("d") , RandomConstant(4, 1)                                              ]),
        Instruction("sha"        , [RandomRegister("d") , RandomConstant(4, 1)                                              ]),

        Instruction("sub"        , [RandomRegister("d") , RandomRegister("d")                                               ]),
        Instruction("sub"        , [Register("d15")     , RandomRegister("d")   , RandomRegister("d")                       ]),
        Instruction("sub"        , [RandomRegister("d") , Register("d15")       , RandomRegister("d")                       ]),
        Instruction("sub.a"      , [Register("a10")     , RandomConstant(8, 0)                                              ]),
        Instruction("subs"       , [RandomRegister("d") , RandomRegister("d")                                               ]),

        Instruction("xor"        , [RandomRegister("d") , RandomRegister("d")                                               ]),

        Instruction("lea"        , [RandomRegister("a") , RandomRegisterOffset("a", 16, 1)                                  ]),
# BOL insn
        Instruction("jeq"        , [RandomRegister("d") , RandomConstant(4, 1)  , JumpOffset(15)                            ]),
        Instruction("jne"        , [RandomRegister("d") , RandomConstant(4, 1)  , JumpOffset(15)                            ]),
        Instruction("jge"        , [RandomRegister("d") , RandomConstant(4, 1)  , JumpOffset(15)                            ]),
        Instruction("jge.u"      , [RandomRegister("d") , RandomConstant(4, 0)  , JumpOffset(15)                            ]),
        Instruction("jlt"        , [RandomRegister("d") , RandomConstant(4, 1)  , JumpOffset(15)                            ]),
        Instruction("jlt.u"      , [RandomRegister("d") , RandomConstant(4, 0)  , JumpOffset(15)                            ]),
        Instruction("jned"       , [RandomRegister("d") , RandomConstant(4, 1)  , JumpOffset(15)                            ]),
        Instruction("jnei"       , [RandomRegister("d") , RandomConstant(4, 1)  , JumpOffset(15)                            ]),
# BRN insn
        Instruction("jnz.t"      , [RandomRegister("d") , RandomConstant(4, 0)  , JumpOffset(15)                            ]),
        Instruction("jz.t"       , [RandomRegister("d") , RandomConstant(4, 0)  , JumpOffset(15)                            ]),
# BRR insn
        Instruction("jeq"        , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jne"        , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jeq.a"      , [RandomRegister("a") , RandomRegister("a")   , JumpOffset(15)                            ]),
        Instruction("jne.a"      , [RandomRegister("a") , RandomRegister("a")   , JumpOffset(15)                            ]),
        Instruction("jge"        , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jge.u"      , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jlt"        , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jlt.u"      , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jned"       , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jnei"       , [RandomRegister("d") , RandomRegister("d")   , JumpOffset(15)                            ]),
        Instruction("jz.a"       , [RandomRegister("a") , JumpOffset(15)                                                    ]),
        Instruction("jnz.a"      , [RandomRegister("a") , JumpOffset(15)                                                    ]),
# RC insn
        Instruction("and"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("andn"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("nand"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("nor"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("or"         , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("orn"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("sh"         , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("sh.h"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("sha"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("sha.h"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("shas"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("xnor"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("xor"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("absdif"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("absdifs"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("add"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("addc"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("adds"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("adds.u"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("addx"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("and.eq"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("and.ge"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("and.ge.u"   , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("and.lt"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("and.lt.u"   , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("and.ne"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("eq"         , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("eqany.b"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("eqany.h"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("ge"         , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("ge.u"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("lt"         , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("lt.u"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("max"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("max.u"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("min"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("min.u"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("ne"         , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("or.eq"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("or.ge"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("or.ge.u"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("or.lt"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("or.lt.u"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("or.ne"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("rsub"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("rsubs"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("rsubs.u"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("sh.eq"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("sh.ge"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("sh.ge.u"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("sh.lt"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("sh.lt.u"    , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("sh.ne"      , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("xor.eq"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("xor.ge"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("xor.ge.u"   , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("xor.lt"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("xor.lt.u"   , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
        Instruction("xor.ne"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("mul"        , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("mul"        , [RandomRegister64("e") , RandomRegister("d") , RandomConstant(9,1)                       ]),
        Instruction("muls"       , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,1)                       ]),
        Instruction("mul.u"      , [RandomRegister64("e") , RandomRegister("d") , RandomConstant(9,0)                       ]),
        Instruction("muls.u"     , [RandomRegister("d") , RandomRegister("d")   , RandomConstant(9,0)                       ]),
# RCR format
        Instruction("madd"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(9,1)     ]),
        Instruction("madd"      , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,1)   ]),
        Instruction("madds"     , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(9,1)     ]),
        Instruction("madds"     , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,1)   ]),
        Instruction("madd.u"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,0)   ]),
        Instruction("madds.u"   , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(9,0)     ]),
        Instruction("madds.u"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,0)   ]),

        Instruction("msub"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(9,1)     ]),
        Instruction("msub"      , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,1)   ]),
        Instruction("msubs"     , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(9,1)     ]),
        Instruction("msubs"     , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,1)   ]),
        Instruction("msub.u"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,0)   ]),
        Instruction("msubs.u"   , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(9,0)     ]),
        Instruction("msubs.u"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomConstant(9,0)   ]),
# RLC format
        Instruction("addi"      , [RandomRegister("d")  , RandomRegister("d")  , RandomConstant(16,1)                       ]),
        Instruction("addih"     , [RandomRegister("d")  , RandomRegister("d")  , RandomConstant(16,0)                       ]),
        Instruction("addih.a"   , [RandomRegister("a")  , RandomRegister("a")  , RandomConstant(16,0)                       ]),
# RR format
        Instruction("abs"       , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("abs.b"     , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("abs.h"     , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("absdif"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("absdif.b"  , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("absdif.h"  , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("absdifs"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("absdifs.h" , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("abss"      , [RandomRegister("d")  , RandomRegister("d") ,                                             ]),
        Instruction("abss.h"    , [RandomRegister("d")  , RandomRegister("d") ,                                             ]),
        Instruction("add"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("add.b"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("add.h"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("addc"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("adds"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("adds.h"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("adds.hu"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("adds.u"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("addx"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("and.eq"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("and.ge"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("and.ge.u"  , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("and.lt"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("and.lt.u"  , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("and.ne"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("eq"        , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("eq.b"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("eq.h"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("eq.w"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("eqany.b"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("eqany.h"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("ge"        , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("ge.u"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt"        , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt.u"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt"        , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt.b"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt.bu"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt.h"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt.hu"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt.w"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("lt.wu"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("max"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("max.u"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("max.b"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("max.bu"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("max.h"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("max.hu"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("min"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("min.u"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("min.b"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("min.bu"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("min.h"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("min.hu"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("mov"       , [RandomRegister("d")  , RandomRegister("d") ,                                             ]),
        Instruction("ne"        , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("or.eq"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("or.ge"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("or.ge.u"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("or.lt"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("or.lt.u"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("or.ne"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sat.b"     , [RandomRegister("d")  , RandomRegister("d") ,                                             ]),
        Instruction("sat.bu"    , [RandomRegister("d")  , RandomRegister("d") ,                                             ]),
        Instruction("sat.h"     , [RandomRegister("d")  , RandomRegister("d") ,                                             ]),
        Instruction("sat.hu"    , [RandomRegister("d")  , RandomRegister("d") ,                                             ]),
        Instruction("sh.eq"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sh.ge"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sh.ge.u"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sh.lt"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sh.lt.u"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sh.ne"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sub"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sub.b"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sub.h"     , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("subc"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("subs"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("subs.u"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("subs.h"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("subs.hu"   , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("subx"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("xor.eq"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("xor.ge"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("xor.ge.u"  , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("xor.lt"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("xor.lt.u"  , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("xor.ne"    , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
# shift_logical
        Instruction("and"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("andn"      , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("clo"       , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("clo.h"     , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("cls"       , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("cls.h"     , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("clz"       , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("clz.h"     , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("nand"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("nor"       , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("or"        , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("orn"       , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("sh"        , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("sh.h"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("sha"       , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("sha.h"     , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("shas"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("xnor"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("xor"       , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
# address
        Instruction("add.a"     , [RandomRegister("a")  , RandomRegister("a"), RandomRegister("a")                          ]),
        Instruction("addsc.a"   , [RandomRegister("a")  , RandomRegister("a"), RandomRegister("d"), RandomConstant(2,0)     ]),
        Instruction("addsc.at"  , [RandomRegister("a")  , RandomRegister("a"), RandomRegister("d")                          ]),
        Instruction("eq.a"      , [RandomRegister("d")  , RandomRegister("a"), RandomRegister("a")                          ]),
        Instruction("eqz.a"     , [RandomRegister("d")  , RandomRegister("a"),                                              ]),
        Instruction("ge.a"      , [RandomRegister("d")  , RandomRegister("a"), RandomRegister("a")                          ]),
        Instruction("lt.a"      , [RandomRegister("d")  , RandomRegister("a"), RandomRegister("a")                          ]),
        Instruction("mov.a"     , [RandomRegister("a")  , RandomRegister("d")                                               ]),
        Instruction("mov.aa"    , [RandomRegister("a")  , RandomRegister("a")                                               ]),
        Instruction("mov.d"     , [RandomRegister("d")  , RandomRegister("a")                                               ]),
        Instruction("ne.a"      , [RandomRegister("d")  , RandomRegister("a"), RandomRegister("a")                          ]),
        Instruction("nez.a"     , [RandomRegister("d")  , RandomRegister("a")                                               ]),
        Instruction("sub.a"     , [RandomRegister("a")  , RandomRegister("a"), RandomRegister("a")                          ]),
# division
        Instruction("bmerge"    , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("bsplit"    , [RandomRegister64("e"), RandomRegister("d")                                               ]),
        Instruction("dvinit"    , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("dvinit.h"  , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("dvinit.b"  , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("dvinit.u"  , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("dvinit.hu" , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("dvinit.bu" , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
        Instruction("parity"    , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("unpack"    , [RandomRegister64("e"), RandomRegister("d")                                               ]),
        #Instruction("div"       , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
        #Instruction("div.u"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                          ]),
#RR1 format
        Instruction("mul.h"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("mul.h"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("mul.h"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("mul.h"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("mulm.h"    , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("mulm.h"    , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("mulm.h"    , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("mulm.h"    , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("mulr.h"    , [RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("mulr.h"    , [RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("mulr.h"    , [RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("mulr.h"    , [RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("mul.q"     , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0)           ]),
        Instruction("mul.q"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0)           ]),
        Instruction("mul.q"     , [RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "l") , RandomConstant(1,0) ]),
        Instruction("mul.q"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "l") , RandomConstant(1,0) ]),
        Instruction("mul.q"     , [RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l") , RandomConstant(1,0) ]),
        Instruction("mul.q"     , [RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u") , RandomConstant(1,0) ]),
        Instruction("mulr.q"    , [RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l") , RandomConstant(1,0) ]),
        Instruction("mulr.q"    , [RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u") , RandomConstant(1,0) ]),
#RR2 format
        Instruction("mul"       , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                                ]),
        Instruction("mul"       , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                                ]),
        Instruction("muls"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                                ]),
        Instruction("mul.u"     , [RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")                                ]),
        Instruction("muls.u"    , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")                                ]),
#RRR format
        Instruction("cadd"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")           ]),
        Instruction("caddn"     , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")           ]),
        Instruction("csub"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")           ]),
        Instruction("csubn"     , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")           ]),
        Instruction("sel"       , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")           ]),
        Instruction("seln"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")           ]),

        Instruction("dvadj"     , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d")                              ]),
        Instruction("ixmax"     , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d")                              ]),
        Instruction("ixmax.u"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d")                              ]),
        Instruction("ixmin"     , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d")                              ]),
        Instruction("ixmin.u"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d")                              ]),
        Instruction("pack"      , [RandomRegister("d")  , RandomRegister64("e"), RandomRegister("d")                              ]),
#RRR2 format
        Instruction("madd"      , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("madd"      , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("madds"     , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("madds"     , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("madd.u"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("madds.u"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("madds.u"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("msub"      , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("msub"      , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("msubs"     , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("msubs"     , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("msub.u"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("msubs.u"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d")         ]),
        Instruction("msubs.u"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d")         ]),
#RRR1 format
        Instruction("madd.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("madd.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("madd.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("madd.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("madds.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("madds.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("madds.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("madds.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),

        Instruction("madd.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("madd.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("madds.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("maddr.h"   , [RandomRegister("d")  , RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddrs.h"  , [RandomRegister("d")  , RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddr.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("maddr.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("maddrs.q"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("maddrs.q"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),

        Instruction("maddsu.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddsu.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddsu.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddsu.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddsus.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddsus.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddsus.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddsus.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddsum.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddsum.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddsum.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddsum.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddsums.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddsums.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddsums.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddsums.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddsur.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddsur.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddsur.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddsur.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("maddsurs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("maddsurs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("maddsurs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("maddsurs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),

        Instruction("msub.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msub.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msub.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msub.h"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubs.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubs.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubs.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubs.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubm.h"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubms.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubr.h"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubrs.h"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),

        Instruction("msub.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msub.q"    , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegister("d"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msubs.q"   , [RandomRegister64("e"), RandomRegister64("e"), RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msubr.h"   , [RandomRegister("d")  , RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubrs.h"  , [RandomRegister("d")  , RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubr.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msubr.q"   , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),
        Instruction("msubrs.q"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "l"), RandomRegisterMode("d", "l"), RandomConstant(1,0) ]),
        Instruction("msubrs.q"  , [RandomRegister("d")  , RandomRegister("d")  , RandomRegisterMode("d", "u"), RandomRegisterMode("d", "u"), RandomConstant(1,0) ]),

        Instruction("msubad.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubad.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubad.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubad.h"  , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubads.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubads.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubads.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubads.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubadm.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubadm.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubadm.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubadm.h" , [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubadms.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubadms.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubadms.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubadms.h", [RandomRegister64("e"), RandomRegister64("e"), RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubadr.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubadr.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubadr.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubadr.h" , [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),
        Instruction("msubadrs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ll"), RandomConstant(1,0) ]),
        Instruction("msubadrs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "lu"), RandomConstant(1,0) ]),
        Instruction("msubadrs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "ul"), RandomConstant(1,0) ]),
        Instruction("msubadrs.h", [RandomRegister("d")  , RandomRegister("d")  , RandomRegister("d"), RandomRegisterMode("d", "uu"), RandomConstant(1,0) ]),

        Instruction("add.f"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("sub.f"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("cmp.f"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("mul.f"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("div.f"       , [RandomRegister("d")  , RandomRegister("d") , RandomRegister("d")                         ]),
        Instruction("ftoi"        , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        #Instruction("ftouz"        , [RandomRegister("d")  , RandomRegister("d")                                              ]),
        Instruction("itof"        , [RandomRegister("d")  , RandomRegister("d")                                               ]),
        Instruction("madd.f"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")     ]),
        Instruction("msub.f"      , [RandomRegister("d")  , RandomRegister("d"), RandomRegister("d"), RandomRegister("d")     ]),
        Instruction("extr"        , [RandomRegister("d")  , RandomRegister("d"), RandomPosWidthPair(5, 5)]),
        Instruction("extr.u"        , [RandomRegister("d")  , RandomRegister("d"), RandomPosWidthPair(5, 5)]),
        Instruction("imask"        , [RandomRegister64("e")  , RandomConstant(4,0), RandomPosWidthPair(5, 5)]),
        Instruction("imask"        , [RandomRegister64("e")  , RandomRegister("d"), RandomPosWidthPair(5, 5)]),
        #Instruction("restore"  , [RandomRegister("d")                                                                         ]),
       ]

